export const DEVICE_CATALOG = [
  {
    group: 'instruments',
    key: 'centrifuge',
    name: '離心機',
    subtitle: '樣品高速分離',
    widthMm: 600,
    depthMm: 600,
    heightMm: 900,
    accent: '#38bdf8',
    theme: 'cool',
  },
  {
    group: 'instruments',
    key: 'pcr_machine',
    name: 'PCR 儀',
    subtitle: '核酸擴增分析',
    widthMm: 500,
    depthMm: 400,
    heightMm: 350,
    accent: '#f472b6',
    theme: 'warm',
  },
  {
    group: 'instruments',
    key: 'microscope',
    name: '顯微鏡',
    subtitle: '光學細胞觀察',
    widthMm: 400,
    depthMm: 350,
    heightMm: 600,
    accent: '#34d399',
    theme: 'cool',
  },
  {
    group: 'instruments',
    key: 'auto_analyzer',
    name: '自動分析儀',
    subtitle: '全自動生化分析',
    widthMm: 900,
    depthMm: 650,
    heightMm: 1400,
    accent: '#fb923c',
    theme: 'warm',
  },
  {
    group: 'instruments',
    key: 'spectrophotometer',
    name: '分光光度計',
    subtitle: '光譜吸收分析',
    widthMm: 500,
    depthMm: 400,
    heightMm: 250,
    accent: '#c084fc',
    theme: 'cool',
  },
  {
    group: 'instruments',
    key: 'incubator',
    name: '培養箱',
    subtitle: '溫控培養設備',
    widthMm: 700,
    depthMm: 600,
    heightMm: 1600,
    accent: '#a78bfa',
    theme: 'warm',
  },
  {
    group: 'instruments',
    key: 'automation_track',
    name: '自動化軌道',
    subtitle: '樣本自動傳輸',
    widthMm: 1400,
    depthMm: 300,
    heightMm: 400,
    accent: '#94a3b8',
    theme: 'neutral',
  },
  {
    group: 'instruments',
    key: 'pure_water',
    name: '超純水機',
    subtitle: '實驗級超純水',
    widthMm: 350,
    depthMm: 380,
    heightMm: 520,
    accent: '#22d3ee',
    theme: 'cool',
  },
  {
    group: 'furniture',
    key: 'bench',
    name: '實驗桌',
    subtitle: '模組化作業平台',
    widthMm: 1400,
    depthMm: 700,
    heightMm: 800,
    accent: '#60a5fa',
    theme: 'neutral',
  },
  {
    group: 'furniture',
    key: 'hood',
    name: '排煙櫃',
    subtitle: '高風量安全排氣',
    widthMm: 1200,
    depthMm: 850,
    heightMm: 2200,
    accent: '#fb7185',
    theme: 'warn',
  },
  {
    group: 'furniture',
    key: 'sink',
    name: '洗滌槽',
    subtitle: '清洗與排水模組',
    widthMm: 900,
    depthMm: 650,
    heightMm: 900,
    accent: '#22c55e',
    theme: 'cool',
  },
  {
    group: 'furniture',
    key: 'fridge',
    name: '冰箱',
    subtitle: '冷藏樣品保存',
    widthMm: 700,
    depthMm: 700,
    heightMm: 1800,
    accent: '#22c55e',
    theme: 'cool',
  },
  {
    group: 'furniture',
    key: 'ultra_low_freezer',
    name: '超低溫冰箱',
    subtitle: '深冷保存設備',
    widthMm: 800,
    depthMm: 800,
    heightMm: 2000,
    accent: '#14b8a6',
    theme: 'cool',
  },
];

export const ZONE_CATALOG = [
  {
    key: 'zone_sample_reception',
    name: '樣品收發區',
    subtitle: 'Sample Reception',
    widthMm: 2600,
    depthMm: 1400,
    color: '#38bdf8',
  },
  {
    key: 'zone_preprocessing',
    name: '前處理區',
    subtitle: 'Pre-processing',
    widthMm: 2800,
    depthMm: 1600,
    color: '#f59e0b',
  },
  {
    key: 'zone_analysis',
    name: '分析區',
    subtitle: 'Analysis',
    widthMm: 3000,
    depthMm: 2000,
    color: '#22c55e',
  },
  {
    key: 'zone_data_mgmt',
    name: '資料管理區',
    subtitle: 'Data Management',
    widthMm: 2200,
    depthMm: 1400,
    color: '#a78bfa',
  },
  {
    key: 'zone_safety_waste',
    name: '安全/廢棄物區',
    subtitle: 'Safety / Waste',
    widthMm: 2400,
    depthMm: 1600,
    color: '#ef4444',
  },
];

export const WALL_CATALOG = [
  {
    key: 'wall_h_full',
    name: '水平隔牆',
    subtitle: '2000×120mm · 120mm 厚',
    lengthMm: 2000,
    thicknessMm: 120,
    heightMm: 2800,
    orientation: 'h',
  },
  {
    key: 'wall_v_full',
    name: '垂直隔牆',
    subtitle: '120×2000mm · 120mm 厚',
    lengthMm: 2000,
    thicknessMm: 120,
    heightMm: 2800,
    orientation: 'v',
  },
  {
    key: 'wall_h_panel',
    name: '水平隔板',
    subtitle: '1600×60mm · 60mm 厚',
    lengthMm: 1600,
    thicknessMm: 60,
    heightMm: 2800,
    orientation: 'h',
  },
  {
    key: 'wall_v_panel',
    name: '垂直隔板',
    subtitle: '60×1600mm · 60mm 厚',
    lengthMm: 1600,
    thicknessMm: 60,
    heightMm: 2800,
    orientation: 'v',
  },
  {
    key: 'wall_h_half',
    name: '水平半牆',
    subtitle: '1200×100mm · 100mm 厚',
    lengthMm: 1200,
    thicknessMm: 100,
    heightMm: 1200,
    orientation: 'h',
  },
  {
    key: 'wall_v_half',
    name: '垂直半牆',
    subtitle: '100×1200mm · 100mm 厚',
    lengthMm: 1200,
    thicknessMm: 100,
    heightMm: 1200,
    orientation: 'v',
  },
];

export const DEVICE_BY_KEY = new Map(DEVICE_CATALOG.map((item) => [item.key, item]));
export const ZONE_BY_KEY = new Map(ZONE_CATALOG.map((item) => [item.key, item]));
export const WALL_BY_KEY = new Map(WALL_CATALOG.map((item) => [item.key, item]));
